spring:
  application:
    name: product-service
  r2dbc:
    password: postgres
    username: postgres
    url: r2dbc:postgresql://localhost:5432/postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration


logging:
  level:
    org.springframework.data: DEBUG
    org.springframework.data.r2dbc: DEBUG