spring:
  application:
    name: product-service
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 250
      maximum-pool-size: 20
      minimum-idle: 15
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
