spring:
  application:
    name: product-service
  r2dbc:
    password: postgres
    username: postgres
    url: r2dbc:postgresql://localhost:5432/postgres
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public